[project]
name = 'smartcontract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST1VZ3YGJKKC8JSSWMS4EZDXXJM7QWRBEZ0ZWM64E.real-World-Asset-Trait'

[[project.requirements]]
contract_id = 'ST390VFVZJA4WP7QSZN0RTSGQDAG2P9NPN3X1ATDX.pxttest1'

[[project.requirements]]
contract_id = 'STM6S3AESTK9NAYE3Z7RS00T11ER8JJCDNTKG711.nft-trait'

[[project.requirements]]
contract_id = 'STM6S3AESTK9NAYE3Z7RS00T11ER8JJCDNTKG711.sip-010-trait'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.Apttokens]
path = 'contracts/Apttokens.clar'
clarity_version = 3
epoch = 3.1

[contracts.KYC]
path = 'contracts/KYC.clar'
clarity_version = 3
epoch = 3.1

[contracts.Token]
path = 'contracts/Token.clar'
clarity_version = 3
epoch = 3.1

[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 3
epoch = 3.1

[contracts.marketplace-ft-holder]
path = 'contracts/marketplace-ft-holder.clar'
clarity_version = 3
epoch = 3.1

[contracts.pool]
path = 'contracts/pool.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
